### ISSUE TITLE
Upgrade to SBT 1.0.0

### ISSUE THREAD

**Issue by nrinaudo** [nrinaudo/kantan.sbt#12]
- [x] sbt-site: https://github.com/sbt/sbt-site/pull/107
- [x] sbt-scoverage: https://github.com/scoverage/sbt-scoverage/issues/233
- [x] sbt-doctest: https://github.com/tkawachi/sbt-doctest/pull/96
- [x] sbt-ghpages: https://github.com/sbt/sbt-ghpages/issues/36
- [x] sbt-scalastyle: https://github.com/scalastyle/scalastyle-sbt-plugin/issues/62
- [x] wartremover: https://github.com/wartremover/wartremover/issues/393

**Comment by matthewfarwell** [comment]
Release scalastyle v1.0.0 which includes sbt 1.0 support.

**Comment by nrinaudo** [comment]
Thanks for taking the time to let me know!
